// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXOawTWMzHaFVX7yQx-dZiRr5NUvFJrnk',
    appId: '1:531188786802:web:c0fb8c0d74a2d70acc44eb',
    messagingSenderId: '531188786802',
    projectId: 'tourmauricehabe-218ab',
    authDomain: 'tourmauricehabe-218ab.firebaseapp.com',
    storageBucket: 'tourmauricehabe-218ab.appspot.com',
    measurementId: 'G-DF27733H81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVUTY5jN_J5-Y4babY-w6GSpCP-hwM6mI',
    appId: '1:531188786802:android:610b3d2e79f68e25cc44eb',
    messagingSenderId: '531188786802',
    projectId: 'tourmauricehabe-218ab',
    storageBucket: 'tourmauricehabe-218ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUR6LypEeXVHEm29JIRCIA-Q0ogqNDbQU',
    appId: '1:531188786802:ios:5c893bc619113ad9cc44eb',
    messagingSenderId: '531188786802',
    projectId: 'tourmauricehabe-218ab',
    storageBucket: 'tourmauricehabe-218ab.appspot.com',
    iosBundleId: 'com.example.tourMaurice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUR6LypEeXVHEm29JIRCIA-Q0ogqNDbQU',
    appId: '1:531188786802:ios:c7a149812aaeebaecc44eb',
    messagingSenderId: '531188786802',
    projectId: 'tourmauricehabe-218ab',
    storageBucket: 'tourmauricehabe-218ab.appspot.com',
    iosBundleId: 'com.example.tourMaurice.RunnerTests',
  );
}
